// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public interface BigIntegerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.BigInteger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
