// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public interface DelRequestVersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.DelRequestVers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 k = 1;</code>
   * @return The k.
   */
  long getK();

  /**
   * <code>int64 vers = 2;</code>
   * @return The vers.
   */
  long getVers();
}
