// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_Reply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_SetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_SetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_DelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_DelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_DelRequestVers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_DelRequestVers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_TestAndSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_TestAndSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_VTripla_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_VTripla_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_BigInteger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_BigInteger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"\034\n\014HelloR" +
      "equest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007me" +
      "ssage\030\001 \001(\t\"\026\n\005Reply\022\r\n\005error\030\001 \001(\t\".\n\nS" +
      "etRequest\022\t\n\001k\030\001 \001(\003\022\n\n\002ts\030\002 \001(\003\022\t\n\001d\030\003 " +
      "\001(\003\"\027\n\nGetRequest\022\t\n\001k\030\001 \001(\003\"\027\n\nDelReque" +
      "st\022\t\n\001k\030\001 \001(\003\")\n\016DelRequestVers\022\t\n\001k\030\001 \001" +
      "(\003\022\014\n\004vers\030\002 \001(\003\"L\n\021TestAndSetRequest\022\t\n" +
      "\001k\030\001 \001(\003\022\036\n\001v\030\002 \001(\0132\023.helloworld.VTripla" +
      "\022\014\n\004vers\030\003 \001(\003\".\n\007VTripla\022\014\n\004vers\030\001 \001(\003\022" +
      "\n\n\002ts\030\002 \001(\003\022\t\n\001d\030\003 \001(\003\"\033\n\nBigInteger\022\r\n\005" +
      "value\030\001 \001(\0142\250\003\n\007Greeter\022>\n\010SayHello\022\030.he" +
      "lloworld.HelloRequest\032\026.helloworld.Hello" +
      "Reply\"\000\022C\n\rSayHelloAgain\022\030.helloworld.He" +
      "lloRequest\032\026.helloworld.HelloReply\"\000\0222\n\003" +
      "set\022\026.helloworld.SetRequest\032\021.helloworld" +
      ".Reply\"\000\0222\n\003get\022\026.helloworld.GetRequest\032" +
      "\021.helloworld.Reply\"\000\0222\n\003del\022\026.helloworld" +
      ".DelRequest\032\021.helloworld.Reply\"\000\022:\n\007delV" +
      "ers\022\032.helloworld.DelRequestVers\032\021.hellow" +
      "orld.Reply\"\000\022@\n\ntestAndSet\022\035.helloworld." +
      "TestAndSetRequest\032\021.helloworld.Reply\"\000B6" +
      "\n\033com.keyvalue.web.repositoryB\017HelloWorl" +
      "dProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_helloworld_Reply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_Reply_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_helloworld_SetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_SetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_SetRequest_descriptor,
        new java.lang.String[] { "K", "Ts", "D", });
    internal_static_helloworld_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetRequest_descriptor,
        new java.lang.String[] { "K", });
    internal_static_helloworld_DelRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helloworld_DelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_DelRequest_descriptor,
        new java.lang.String[] { "K", });
    internal_static_helloworld_DelRequestVers_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_helloworld_DelRequestVers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_DelRequestVers_descriptor,
        new java.lang.String[] { "K", "Vers", });
    internal_static_helloworld_TestAndSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_helloworld_TestAndSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_TestAndSetRequest_descriptor,
        new java.lang.String[] { "K", "V", "Vers", });
    internal_static_helloworld_VTripla_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_helloworld_VTripla_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_VTripla_descriptor,
        new java.lang.String[] { "Vers", "Ts", "D", });
    internal_static_helloworld_BigInteger_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_helloworld_BigInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_BigInteger_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
