// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *required VTripla v = 2;
   * </pre>
   *
   * <code>string error = 1;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <pre>
   *required VTripla v = 2;
   * </pre>
   *
   * <code>string error = 1;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
