// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

/**
 * Protobuf type {@code helloworld.SetRequest}
 */
public final class SetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.SetRequest)
    SetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetRequest.newBuilder() to construct.
  private SetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            k_ = input.readInt64();
            break;
          }
          case 16: {

            ts_ = input.readInt64();
            break;
          }
          case 24: {

            d_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.keyvalue.web.repository.HelloWorldProto.internal_static_helloworld_SetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.keyvalue.web.repository.HelloWorldProto.internal_static_helloworld_SetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.keyvalue.web.repository.SetRequest.class, com.keyvalue.web.repository.SetRequest.Builder.class);
  }

  public static final int K_FIELD_NUMBER = 1;
  private long k_;
  /**
   * <code>int64 k = 1;</code>
   * @return The k.
   */
  @java.lang.Override
  public long getK() {
    return k_;
  }

  public static final int TS_FIELD_NUMBER = 2;
  private long ts_;
  /**
   * <code>int64 ts = 2;</code>
   * @return The ts.
   */
  @java.lang.Override
  public long getTs() {
    return ts_;
  }

  public static final int D_FIELD_NUMBER = 3;
  private long d_;
  /**
   * <code>int64 d = 3;</code>
   * @return The d.
   */
  @java.lang.Override
  public long getD() {
    return d_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (k_ != 0L) {
      output.writeInt64(1, k_);
    }
    if (ts_ != 0L) {
      output.writeInt64(2, ts_);
    }
    if (d_ != 0L) {
      output.writeInt64(3, d_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (k_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, k_);
    }
    if (ts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, ts_);
    }
    if (d_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, d_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.keyvalue.web.repository.SetRequest)) {
      return super.equals(obj);
    }
    com.keyvalue.web.repository.SetRequest other = (com.keyvalue.web.repository.SetRequest) obj;

    if (getK()
        != other.getK()) return false;
    if (getTs()
        != other.getTs()) return false;
    if (getD()
        != other.getD()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + K_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getK());
    hash = (37 * hash) + TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTs());
    hash = (37 * hash) + D_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getD());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.keyvalue.web.repository.SetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.keyvalue.web.repository.SetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.keyvalue.web.repository.SetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.keyvalue.web.repository.SetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.keyvalue.web.repository.SetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.SetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.SetRequest)
      com.keyvalue.web.repository.SetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keyvalue.web.repository.HelloWorldProto.internal_static_helloworld_SetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keyvalue.web.repository.HelloWorldProto.internal_static_helloworld_SetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keyvalue.web.repository.SetRequest.class, com.keyvalue.web.repository.SetRequest.Builder.class);
    }

    // Construct using com.keyvalue.web.repository.SetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      k_ = 0L;

      ts_ = 0L;

      d_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.keyvalue.web.repository.HelloWorldProto.internal_static_helloworld_SetRequest_descriptor;
    }

    @java.lang.Override
    public com.keyvalue.web.repository.SetRequest getDefaultInstanceForType() {
      return com.keyvalue.web.repository.SetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.keyvalue.web.repository.SetRequest build() {
      com.keyvalue.web.repository.SetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.keyvalue.web.repository.SetRequest buildPartial() {
      com.keyvalue.web.repository.SetRequest result = new com.keyvalue.web.repository.SetRequest(this);
      result.k_ = k_;
      result.ts_ = ts_;
      result.d_ = d_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.keyvalue.web.repository.SetRequest) {
        return mergeFrom((com.keyvalue.web.repository.SetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.keyvalue.web.repository.SetRequest other) {
      if (other == com.keyvalue.web.repository.SetRequest.getDefaultInstance()) return this;
      if (other.getK() != 0L) {
        setK(other.getK());
      }
      if (other.getTs() != 0L) {
        setTs(other.getTs());
      }
      if (other.getD() != 0L) {
        setD(other.getD());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.keyvalue.web.repository.SetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.keyvalue.web.repository.SetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long k_ ;
    /**
     * <code>int64 k = 1;</code>
     * @return The k.
     */
    @java.lang.Override
    public long getK() {
      return k_;
    }
    /**
     * <code>int64 k = 1;</code>
     * @param value The k to set.
     * @return This builder for chaining.
     */
    public Builder setK(long value) {
      
      k_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 k = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearK() {
      
      k_ = 0L;
      onChanged();
      return this;
    }

    private long ts_ ;
    /**
     * <code>int64 ts = 2;</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return ts_;
    }
    /**
     * <code>int64 ts = 2;</code>
     * @param value The ts to set.
     * @return This builder for chaining.
     */
    public Builder setTs(long value) {
      
      ts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ts = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTs() {
      
      ts_ = 0L;
      onChanged();
      return this;
    }

    private long d_ ;
    /**
     * <code>int64 d = 3;</code>
     * @return The d.
     */
    @java.lang.Override
    public long getD() {
      return d_;
    }
    /**
     * <code>int64 d = 3;</code>
     * @param value The d to set.
     * @return This builder for chaining.
     */
    public Builder setD(long value) {
      
      d_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 d = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearD() {
      
      d_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helloworld.SetRequest)
  }

  // @@protoc_insertion_point(class_scope:helloworld.SetRequest)
  private static final com.keyvalue.web.repository.SetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.keyvalue.web.repository.SetRequest();
  }

  public static com.keyvalue.web.repository.SetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetRequest>() {
    @java.lang.Override
    public SetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.keyvalue.web.repository.SetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

