// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public interface SetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.SetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 k = 1;</code>
   * @return The k.
   */
  long getK();

  /**
   * <code>int64 ts = 2;</code>
   * @return The ts.
   */
  long getTs();

  /**
   * <code>int64 d = 3;</code>
   * @return The d.
   */
  long getD();
}
