// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public interface TestAndSetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.TestAndSetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 k = 1;</code>
   * @return The k.
   */
  long getK();

  /**
   * <code>.helloworld.VTripla v = 2;</code>
   * @return Whether the v field is set.
   */
  boolean hasV();
  /**
   * <code>.helloworld.VTripla v = 2;</code>
   * @return The v.
   */
  com.keyvalue.web.repository.VTripla getV();
  /**
   * <code>.helloworld.VTripla v = 2;</code>
   */
  com.keyvalue.web.repository.VTriplaOrBuilder getVOrBuilder();

  /**
   * <code>int64 vers = 3;</code>
   * @return The vers.
   */
  long getVers();
}
