// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.keyvalue.web.repository;

public interface VTriplaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.VTripla)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 vers = 1;</code>
   * @return The vers.
   */
  long getVers();

  /**
   * <code>int64 ts = 2;</code>
   * @return The ts.
   */
  long getTs();

  /**
   * <code>int64 d = 3;</code>
   * @return The d.
   */
  long getD();
}
